# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quiz2TeamD' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'DynamicColor'
pod 'IQKeyboardManagerSwift'
pod 'SkyFloatingLabelTextField'
pod 'DKImagePickerController'

  # Pods for Quiz2TeamD

end
